export default {
  getData() {
    return {
      uid: "uid3d6b3a5c38d64bc08786f066a6490691",
      w: 1000,
      h: 650,
      x: 0,
      y: 0,
      dock: 0,
      anchor: [],
      zIndex: 0,
      borderStyle: {
        borderType: "normal",
        borderSide: "all",
        borderRadius: 0,
        allSetting: {
          style: "solid",
          width: 0,
          color: "#000000",
          padding: 0,
        },
        singleSetting: [
          {
            name: "Left",
            check: false,
            style: "solid",
            width: 0,
            color: "#000000",
            padding: 0,
          },
          {
            name: "Top",
            check: false,
            style: "solid",
            width: 0,
            color: "#000000",
            padding: 0,
          },
          {
            name: "Right",
            check: false,
            style: "solid",
            width: 0,
            color: "#000000",
            padding: 0,
          },
          {
            name: "Bottom",
            check: false,
            style: "solid",
            width: 0,
            color: "#000000",
            padding: 0,
          },
        ],
        decorationSetting: {
          style: "1",
          borderConfig: {
            color1: "#4fd2dd",
            color2: "#235fa7",
            reverse: false,
            needResize: true,
            backgroundColor: "transparent",
            title: "标题",
            titleWidth: 250,
            titleStyle: {
              fontSize: 18,
              textAlign: "center",
              color: "#fff",
              fontWeight: "normal",
            },
            dur: 3,
          },
          padding: [15, 15, 15, 15],
        },
      },
      backgroundStyle: {
        color: "white",
        image: {
          url: "",
          repeat: "stretch",
          opacity: 100,
        },
      },
      type: "PageLayoutCmp",
      isDarkModel: false,
      childs: [
        {
          uid: "uid5f077dbc32304dc5abf46d4a71efda7b",
          w: 100,
          h: 100,
          x: 13,
          y: 22,
          dock: 0,
          anchor: [],
          zIndex: 0,
          borderStyle: {
            borderType: "normal",
            borderSide: "all",
            borderRadius: 0,
            allSetting: {
              style: "solid",
              width: 0,
              color: "#000000",
              padding: 0,
            },
            singleSetting: [
              {
                name: "Left",
                check: false,
                style: "solid",
                width: 0,
                color: "#000000",
                padding: 0,
              },
              {
                name: "Top",
                check: false,
                style: "solid",
                width: 0,
                color: "#000000",
                padding: 0,
              },
              {
                name: "Right",
                check: false,
                style: "solid",
                width: 0,
                color: "#000000",
                padding: 0,
              },
              {
                name: "Bottom",
                check: false,
                style: "solid",
                width: 0,
                color: "#000000",
                padding: 0,
              },
            ],
            decorationSetting: {
              style: "1",
              borderConfig: {
                color1: "#4fd2dd",
                color2: "#235fa7",
                reverse: false,
                needResize: true,
                backgroundColor: "transparent",
                title: "标题",
                titleWidth: 250,
                titleStyle: {
                  fontSize: 18,
                  textAlign: "center",
                  color: "#fff",
                  fontWeight: "normal",
                },
                dur: 3,
              },
              padding: [15, 15, 15, 15],
            },
          },
          backgroundStyle: {
            color: "#ffffff00",
            image: {
              url: "",
              repeat: "stretch",
              opacity: 100,
            },
          },
          type: "TextCmp",
          text: "Text",
          fontStyle: {
            fontSize: 14,
            textAlign: "left",
            color: "white",
            fontWeight: "normal",
            wrap: true,
            fontFamily: "",
          },
        },
        {
          uid: "uiddd0fbdb1ea944be4b98f8f761a405a2c",
          w: 100,
          h: 100,
          x: 907,
          y: 597,
          dock: 0,
          anchor: [],
          zIndex: 0,
          borderStyle: {
            borderType: "normal",
            borderSide: "all",
            borderRadius: 0,
            allSetting: {
              style: "solid",
              width: 0,
              color: "#000000",
              padding: 0,
            },
            singleSetting: [
              {
                name: "Left",
                check: false,
                style: "solid",
                width: 0,
                color: "#000000",
                padding: 0,
              },
              {
                name: "Top",
                check: false,
                style: "solid",
                width: 0,
                color: "#000000",
                padding: 0,
              },
              {
                name: "Right",
                check: false,
                style: "solid",
                width: 0,
                color: "#000000",
                padding: 0,
              },
              {
                name: "Bottom",
                check: false,
                style: "solid",
                width: 0,
                color: "#000000",
                padding: 0,
              },
            ],
            decorationSetting: {
              style: "1",
              borderConfig: {
                color1: "#4fd2dd",
                color2: "#235fa7",
                reverse: false,
                needResize: true,
                backgroundColor: "transparent",
                title: "标题",
                titleWidth: 250,
                titleStyle: {
                  fontSize: 18,
                  textAlign: "center",
                  color: "#fff",
                  fontWeight: "normal",
                },
                dur: 3,
              },
              padding: [15, 15, 15, 15],
            },
          },
          backgroundStyle: {
            color: "#ffffff00",
            image: {
              url: "",
              repeat: "stretch",
              opacity: 100,
            },
          },
          type: "TextCmp",
          text: "Text",
          fontStyle: {
            fontSize: 14,
            textAlign: "left",
            color: "white",
            fontWeight: "normal",
            wrap: true,
            fontFamily: "",
          },
        },
      ],
    };
  },
};
